version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-registry.is-tech.vn/lengocnam:1
    ports:
      - "80:80"  # Map port 80 of the host to port 80 of the container
    environment:
      - NODE_ENV=production
